REFACTOR: Replace Python files into CPP files
FppEpitech/Gomoku pull request #22
Opened 2024-11-06 20:26 UTC by AxelF44

I've replace all Python files by CPP Files !

2024-11-06 20:39 UTC, mathieurobert1 requested changes

2024-11-06 20:39 UTC, mathieurobert1 commented on src/Parser/Parser.cpp
> +                throw std::invalid_argument("Format de ligne invalide.");
In english please.

2024-11-06 20:39 UTC, mathieurobert1 commented on src/Parser/Parser.cpp
> +                throw std::invalid_argument("Champ de valeur invalide.");
In english please.

2024-11-06 20:39 UTC, mathieurobert1 commented on src/Parser/Parser.cpp
> +                outputFile << "Erreur dans le format des données : " << line << std::endl;
In english please.

2024-11-06 21:01 UTC, mathieurobert1 approved these changes

2024-11-07 09:06 UTC, theophile-jr approved these changes

2024-11-07 09:06 UTC, merged